export default function Slide10Access() {
  return (
    <div className="deck-grid relative w-screen h-screen overflow-hidden bg-bg text-text">
      <div className="relative flex h-full flex-col px-[7vw] py-[6vh]">
        <div className="flex items-center justify-between font-body text-[1vw] font-bold uppercase tracking-[.24em] text-primary"><span>09 / Access</span><span className="text-muted">RiderLink</span></div>
        <div className="mt-[7vh] grid flex-1 grid-cols-[1fr_1.05fr] gap-[9vw]">
          <div className="flex items-center justify-center"><div className="paper-shadow w-[24vw] border border-primary/10 bg-[#fbf9f5] p-[1.8vw]"><div className="flex items-center gap-[.75vw] font-display text-[1.35vw] font-bold tracking-[-.04em]"><span className="grid h-[2.4vw] w-[2.4vw] place-items-center rounded-[.4vw] bg-accent text-primary">R</span>RiderLink</div><div className="mt-[4vh] text-center"><div className="font-display text-[2vw] font-bold">Welcome back</div><div className="mt-[.8vh] font-body text-[1vw] text-muted">Sign in to access your operations desk</div></div><div className="mt-[3.2vh] border border-primary/15 bg-bg py-[.85vw] text-center font-body text-[1vw] font-bold">Continue with Google</div><div className="my-[2vh] flex items-center gap-[.7vw] font-body text-[.85vw] text-muted"><span className="h-[.1vw] flex-1 bg-primary/15" />or<span className="h-[.1vw] flex-1 bg-primary/15" /></div><div className="font-body text-[.85vw] font-bold text-primary">Email address</div><div className="mt-[.7vh] border border-primary/15 bg-bg px-[.9vw] py-[.9vw] font-body text-[.95vw] text-muted">Enter your email address</div><div className="mt-[1.3vw] bg-primary py-[.9vw] text-center font-body text-[1vw] font-bold text-[#f7f3ec]">Continue</div><div className="mt-[2.5vh] border-t border-primary/10 pt-[1.5vh] text-center font-body text-[.9vw] text-muted">New to RiderLink? <span className="font-bold text-primary">Sign up</span></div></div></div>
          <div className="flex flex-col justify-center"><div className="mb-[2.2vh] font-body text-[1vw] font-bold uppercase tracking-[.24em] text-coral">The right people, in the right place</div><h2 className="max-w-[39vw] font-display text-[4.5vw] font-extrabold leading-[.96] tracking-[-.07em] text-balance">Access that matches the operation</h2><div className="mt-[5vh] space-y-[2vh] font-body text-[1.65vw] leading-[1.12]"><div className="flex gap-[1.2vw]"><span className="font-display font-bold text-accent">01</span><span>Branded RiderLink welcome, sign-in, and sign-up screens</span></div><div className="flex gap-[1.2vw]"><span className="font-display font-bold text-accent">02</span><span>Email and Google sign-in options through Clerk</span></div><div className="flex gap-[1.2vw]"><span className="font-display font-bold text-accent">03</span><span>Protected business routes with a public health endpoint</span></div></div></div>
        </div>
        <div className="flex justify-between font-body text-[1vw] text-muted"><span>Authentication follows the boundary of the business</span><span>10 / 12</span></div>
      </div>
    </div>
  );
}