export default function Slide06FieldMode() {
  return (
    <div className="relative w-screen h-screen overflow-hidden bg-primary text-[#f7f3ec]">
      <div className="absolute -left-[8vw] bottom-[4vh] h-[30vw] w-[30vw] rounded-full border-[1.3vw] border-[#c5d6ce]/20" />
      <div className="relative flex h-full flex-col px-[7vw] py-[6vh]">
        <div className="flex items-center justify-between font-body text-[1vw] font-bold uppercase tracking-[.24em] text-[#c8d4ce]"><span>05 / Field mode</span><span>RiderLink</span></div>
        <div className="mt-[7vh] grid flex-1 grid-cols-[.9fr_1.1fr] gap-[8vw]">
          <div className="flex flex-col justify-center"><div className="mb-[2.3vh] font-body text-[1vw] font-bold uppercase tracking-[.24em] text-accent">For the person moving it</div><h2 className="font-display text-[4.6vw] font-extrabold leading-[.96] tracking-[-.065em]">Field mode for riders</h2><p className="mt-[3vh] max-w-[32vw] font-body text-[1.8vw] leading-[1.15] text-[#dce6df]">See the route, take the next step, keep moving when the network does not.</p><div className="mt-[5vh] space-y-[1.6vh] font-body text-[1.5vw] text-[#dce6df]"><div className="flex gap-[1vw]"><span className="text-accent">01</span><span>See only the deliveries assigned to you</span></div><div className="flex gap-[1vw]"><span className="text-accent">02</span><span>Move each delivery forward with one clear action</span></div><div className="flex gap-[1vw]"><span className="text-accent">03</span><span>Continue working offline and sync queued updates when connection returns</span></div></div></div>
          <div className="flex items-center justify-center gap-[2.5vw]">
            <div className="soft-shadow relative h-[48vh] w-[19vw] rounded-[2vw] border-[.35vw] border-[#dce6df]/50 bg-[#f7f3ec] p-[1vw] text-text"><div className="mx-auto h-[.45vw] w-[4vw] rounded-full bg-primary/25" /><div className="mt-[3vh] font-body text-[.85vw] font-bold uppercase tracking-[.16em] text-muted">My route</div><div className="mt-[1.5vh] font-display text-[1.8vw] font-bold">3 deliveries</div><div className="mt-[3vh] rounded-[.8vw] bg-sage/35 p-[1vw]"><div className="font-display text-[1.15vw] font-bold">RL-1047</div><div className="mt-[.6vh] font-body text-[.95vw] text-muted">Kilimani · Assigned</div><div className="mt-[2vh] h-[2.8vw] rounded-[.5vw] bg-primary text-center pt-[.72vw] font-body text-[.9vw] font-bold text-[#f7f3ec]">Mark picked up</div></div><div className="mt-[1.2vw] rounded-[.8vw] border border-primary/15 p-[1vw]"><div className="font-display text-[1.15vw] font-bold">RL-1046</div><div className="mt-[.6vh] font-body text-[.95vw] text-muted">Lavington · Picked up</div></div><div className="absolute bottom-[1.4vw] left-[1vw] right-[1vw] flex items-center gap-[.6vw] border-t border-primary/10 pt-[1vw] font-body text-[.85vw] text-muted"><span className="h-[.55vw] w-[.55vw] rounded-full bg-primary" /> Online</div></div>
            <div className="w-[15vw] rounded-[1vw] border border-[#c5d6ce]/30 bg-[#1d4946] p-[1.5vw]"><div className="flex items-center gap-[.7vw] font-body text-[.95vw] font-bold text-accent"><span className="h-[.65vw] w-[.65vw] rounded-full bg-accent" /> Connection back</div><div className="mt-[2vh] font-display text-[1.6vw] font-bold">3 updates waiting</div><div className="mt-[1.2vh] font-body text-[1vw] leading-[1.12] text-[#c8d4ce]">Queued safely on the phone. Ready to sync.</div><div className="mt-[2.5vh] h-[.45vw] w-full bg-[#c5d6ce]/25"><div className="h-full w-[78%] bg-accent" /></div></div>
          </div>
        </div>
        <div className="flex justify-between font-body text-[1vw] text-[#c8d4ce]"><span>One clear next step at a time</span><span>06 / 12</span></div>
      </div>
    </div>
  );
}