import { useEffect, useState } from 'react';
import { Check, ChevronRight, MapPin, Phone, Plus, X } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { Link } from 'wouter';
import { useAssignDeliveryRequest, useCancelDeliveryRequest, useGetDeliveryRequest, useListDeliveryRequests, useListRiders, useUpdateDeliveryStatus, getGetDashboardSummaryQueryKey, getGetDeliveryRequestQueryKey, getListActivityQueryKey, getListDeliveryRequestsQueryKey, getListRidersQueryKey } from '@workspace/api-client-react';
import type { DeliveryStatus } from '@workspace/api-client-react';
import { NewDeliveryDialog } from '@/components/delivery-dialog';
import { ErrorState, LoadingRows, StatusBadge, formatDate, formatTime, initials } from '@/components/shell';

export default function Deliveries() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [newOpen, setNewOpen] = useState(false);
  const deliveries = useListDeliveryRequests({ search: search || undefined, status: (status || undefined) as DeliveryStatus | undefined, limit: 100 });
  const queryClient = useQueryClient();
  const selected = useGetDeliveryRequest(selectedId ?? '', { query: { enabled: Boolean(selectedId), queryKey: getGetDeliveryRequestQueryKey(selectedId ?? '') } });
  const riders = useListRiders();
  useEffect(() => { if (!selectedId && deliveries.data?.[0]) setSelectedId(deliveries.data[0].id); }, [deliveries.data, selectedId]);
  const refresh = () => { queryClient.invalidateQueries({ queryKey: getListDeliveryRequestsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); queryClient.invalidateQueries({ queryKey: getListActivityQueryKey({ limit: 8 }) }); queryClient.invalidateQueries({ queryKey: getListRidersQueryKey() }); };
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Operations / Queue</div><h1 className="page-title">Deliveries</h1><p className="page-description">Search every request, see who has it, and move the next handoff forward.</p></div><button className="btn btn-primary" onClick={() => setNewOpen(true)} data-testid="button-new-delivery"><Plus size={15} /> New delivery</button></div>
    <div className="panel"><div className="table-tools"><div className="search-wrap"><input className="input" type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search reference, customer or address" data-testid="input-search-deliveries" /></div><select className="input filter-select" value={status} onChange={(e) => setStatus(e.target.value)} data-testid="select-delivery-status"><option value="">All statuses</option><option value="pending">Pending</option><option value="assigned">Assigned</option><option value="picked_up">Picked up</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div>
      {deliveries.isError ? <div style={{ padding: 18 }}><ErrorState onRetry={() => deliveries.refetch()} /></div> : deliveries.isLoading ? <LoadingRows /> : deliveries.data?.length ? <div className="delivery-list"><div className="delivery-row table-head"><div>Request</div><div>Customer</div><div>Destination</div><div>Rider</div><div>Status</div><div /></div>{deliveries.data.map((item) => <button className={`delivery-row ${selectedId === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelectedId(item.id)} data-testid={`row-delivery-${item.id}`}><div className="delivery-ref">{item.reference}<span className="delivery-sub">{formatDate(item.createdAt)}</span></div><div className="delivery-customer">{item.customerName}<span className="delivery-sub">{item.customerPhone}</span></div><div className="delivery-sub">{item.address}</div><div className="delivery-sub">{item.riderName || 'Unassigned'}</div><div><StatusBadge status={item.status} /></div><ChevronRight size={15} color="hsl(var(--muted-foreground))" /></button>)}</div> : <div className="empty-state"><div className="empty-icon"><MapPin size={19} /></div><strong>No deliveries found</strong><p>Try another search, or create a new request for the queue.</p><button className="btn btn-primary" onClick={() => setNewOpen(true)} data-testid="button-empty-new-delivery">Create first delivery</button></div>}</div>
    {selectedId && <DeliveryDrawer id={selectedId} detail={selected.data} isLoading={selected.isLoading} isError={selected.isError} riders={riders.data ?? []} onClose={() => setSelectedId(null)} onRefresh={refresh} />}
    {newOpen && <NewDeliveryDialog onClose={() => setNewOpen(false)} />}
  </div>;
}

function DeliveryDrawer({ id, detail, isLoading, isError, riders, onClose, onRefresh }: { id: string; detail?: any; isLoading: boolean; isError: boolean; riders: any[]; onClose: () => void; onRefresh: () => void }) {
  const [riderId, setRiderId] = useState('');
  const queryClient = useQueryClient();
  const assign = useAssignDeliveryRequest();
  const cancel = useCancelDeliveryRequest();
  const update = useUpdateDeliveryStatus();
  useEffect(() => { if (detail?.riderId) setRiderId(detail.riderId); }, [detail?.riderId]);
  const finish = () => { queryClient.invalidateQueries({ queryKey: getGetDeliveryRequestQueryKey(id) }); onRefresh(); };
  const move = (next: 'assigned' | 'picked_up') => update.mutate({ id, data: { status: next, version: detail.version, clientEventId: `desk-${Date.now()}` } }, { onSuccess: finish });
  return <div className="drawer" role="presentation" onMouseDown={(e) => { if (e.currentTarget === e.target) onClose(); }}><aside className="drawer-card"><div className="drawer-head"><div>{detail && <><div className="detail-ref">{detail.reference}</div><div className="detail-title">{detail.customerName}</div><StatusBadge status={detail.status} /></>}</div><button className="icon-btn" onClick={onClose} data-testid="button-close-delivery-detail"><X size={15} /></button></div><div className="drawer-body">{isLoading ? <LoadingRows count={5} /> : isError || !detail ? <ErrorState onRetry={onRefresh} /> : <><div className="detail-grid"><div><div className="detail-label">Drop-off</div><div className="detail-value"><MapPin size={13} style={{ verticalAlign: 'middle', marginRight: 4 }} />{detail.address}</div></div><div><div className="detail-label">Customer</div><div className="detail-value"><Phone size={13} style={{ verticalAlign: 'middle', marginRight: 4 }} />{detail.customerPhone}</div></div><div><div className="detail-label">Item</div><div className="detail-value">{detail.itemDescription}</div></div><div><div className="detail-label">Created</div><div className="detail-value">{formatDate(detail.createdAt)} · {formatTime(detail.createdAt)}</div></div></div>
      <div className="detail-section"><div className="detail-section-title">Assignment</div><div style={{ display: 'flex', gap: 8 }}><select className="input" value={riderId} onChange={(e) => setRiderId(e.target.value)} data-testid="select-assign-rider"><option value="">Choose a rider</option>{riders.map((r) => <option key={r.id} value={r.id}>{r.name} · {r.status.replace('_', ' ')}</option>)}</select><button className="btn btn-primary" disabled={!riderId || assign.isPending} onClick={() => assign.mutate({ id, data: { riderId, version: detail.version } }, { onSuccess: finish })} data-testid="button-assign-rider">{assign.isPending ? '…' : <Check size={15} />}</button></div>{assign.isError && <div className="form-hint" style={{ color: 'hsl(var(--destructive))' }}>Assignment changed elsewhere. Refresh and try again.</div>}</div>
      <div className="detail-section"><div className="detail-section-title">Move this delivery</div><div className="action-row">{detail.status === 'pending' && <button className="btn btn-warn" disabled={!detail.riderId || update.isPending} onClick={() => move('assigned')} data-testid="button-mark-assigned">Mark assigned</button>}{detail.status === 'assigned' && <button className="btn btn-warn" disabled={update.isPending} onClick={() => move('picked_up')} data-testid="button-mark-picked-up">Mark picked up</button>}{detail.status !== 'delivered' && detail.status !== 'cancelled' && <button className="btn btn-danger" disabled={cancel.isPending} onClick={() => { if (window.confirm('Cancel this delivery request?')) cancel.mutate({ id }, { onSuccess: finish }); }} data-testid="button-cancel-delivery">Cancel request</button>}</div></div>
      <div className="detail-section"><div className="detail-section-title">Handoff history</div>{detail.events?.length ? detail.events.slice().reverse().map((event: any) => <div className="timeline-item" key={event.id}><span className="timeline-dot" /><div className="timeline-copy"><strong>{event.status.replace('_', ' ')}</strong><p>{event.actorName} · {formatTime(event.createdAt)}{event.note ? ` · ${event.note}` : ''}</p></div></div>) : <div className="panel-note">No events recorded yet.</div>}</div>
    </>}</div></aside></div>;
}