import { useEffect, useMemo, useState } from 'react';
import { Check, Cloud, CloudOff, MapPin, PackageCheck, RefreshCw, Send, UserRound } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { useListMyDeliveries, useSubmitProofOfDelivery, useSyncOfflineEvents, useUpdateDeliveryStatus, getListMyDeliveriesQueryKey, getGetDashboardSummaryQueryKey, getListActivityQueryKey, getGetDeliveryRequestQueryKey } from '@workspace/api-client-react';
import { ErrorState, LoadingRows, StatusBadge } from '@/components/shell';

type OfflineItem = { deliveryId: string; status: 'assigned' | 'picked_up' | 'delivered'; version: number; clientEventId: string };
const queueKey = 'reflex-offline-events';
function readQueue(): OfflineItem[] { try { return JSON.parse(localStorage.getItem(queueKey) ?? '[]') as OfflineItem[]; } catch { return []; } }

export default function RiderMode() {
  const deliveries = useListMyDeliveries();
  const sync = useSyncOfflineEvents();
  const update = useUpdateDeliveryStatus();
  const queryClient = useQueryClient();
  const [online, setOnline] = useState(navigator.onLine);
  const [queue, setQueue] = useState<OfflineItem[]>(readQueue);
  const [podId, setPodId] = useState<string | null>(null);
  useEffect(() => { const on = () => setOnline(true); const off = () => setOnline(false); window.addEventListener('online', on); window.addEventListener('offline', off); return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off); }; }, []);
  const syncQueue = () => { if (!queue.length || !online) return; sync.mutate({ data: { events: queue } }, { onSuccess: () => { localStorage.removeItem(queueKey); setQueue([]); queryClient.invalidateQueries({ queryKey: getListMyDeliveriesQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); } }); };
  useEffect(() => { if (online && queue.length) syncQueue(); }, [online]); // intentionally sync only when connection returns
  const actionable = useMemo(() => deliveries.data?.filter((d) => d.status !== 'delivered' && d.status !== 'cancelled') ?? [], [deliveries.data]);
  const enqueue = (delivery: any, next: OfflineItem['status']) => { const event = { deliveryId: delivery.id, status: next, version: delivery.version, clientEventId: `rider-${Date.now()}` }; if (!online) { const nextQueue = [...queue, event]; localStorage.setItem(queueKey, JSON.stringify(nextQueue)); setQueue(nextQueue); return; } update.mutate({ id: delivery.id, data: event }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListMyDeliveriesQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDeliveryRequestQueryKey(delivery.id) }); queryClient.invalidateQueries({ queryKey: getListActivityQueryKey({ limit: 8 }) }); } }); };
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Field mode / My route</div><h1 className="page-title">Your deliveries.</h1><p className="page-description">One clear next step at a time. Changes wait safely on your phone when the network does not.</p></div><div className="connection-pill" data-testid="status-rider-connection">{online ? <><span className="online-dot" /> Online</> : <><span className="online-dot offline-dot" /> Offline</>}</div></div>
    {queue.length > 0 && <div className="offline-banner" data-testid="banner-offline-queue">{online ? <Cloud size={17} /> : <CloudOff size={17} />}<div style={{ flex: 1 }}><strong>{queue.length} update{queue.length === 1 ? '' : 's'} waiting to sync</strong><div style={{ fontSize: 10, marginTop: 2 }}>{online ? 'Connection is back. Send them when ready.' : 'They will send when you are back online.'}</div></div>{online && <button className="btn btn-warn" onClick={syncQueue} disabled={sync.isPending} data-testid="button-sync-offline-queue"><RefreshCw size={13} /> Sync now</button>}</div>}
    {deliveries.isError ? <ErrorState onRetry={() => deliveries.refetch()} /> : deliveries.isLoading ? <LoadingRows count={3} /> : actionable.length ? actionable.map((delivery) => <RiderDeliveryCard key={delivery.id} delivery={delivery} busy={update.isPending} onMove={enqueue} onPod={() => setPodId(delivery.id)} />) : <div className="empty-state"><div className="empty-icon"><PackageCheck size={19} /></div><strong>Route is clear</strong><p>There are no active deliveries assigned to you right now. Your dispatcher will add the next one here.</p></div>}
    {podId && <PodDialog delivery={deliveries.data?.find((d) => d.id === podId)} onClose={() => setPodId(null)} onDone={() => { setPodId(null); queryClient.invalidateQueries({ queryKey: getListMyDeliveriesQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); }} />}
  </div>;
}

function RiderDeliveryCard({ delivery, busy, onMove, onPod }: { delivery: any; busy: boolean; onMove: (delivery: any, next: OfflineItem['status']) => void; onPod: () => void }) {
  const next = delivery.status === 'assigned' ? 'picked_up' : 'delivered';
  return <article className="rider-delivery-card" data-testid={`card-my-delivery-${delivery.id}`}><div className="rider-delivery-top"><div><div className="rider-delivery-ref">{delivery.reference}</div><div className="rider-delivery-name">{delivery.customerName}</div><div className="delivery-sub"><MapPin size={11} style={{ verticalAlign: 'middle', marginRight: 4 }} />{delivery.address}</div></div><StatusBadge status={delivery.status} /></div><div className="progress-steps">{(['assigned', 'picked_up', 'delivered'] as const).map((step) => <div className={`progress-step ${['assigned', 'picked_up', 'delivered'].indexOf(step) <= ['assigned', 'picked_up', 'delivered'].indexOf(delivery.status) ? 'done' : ''}`} key={step}><i />{step === 'picked_up' ? 'Picked' : step}</div>)}</div><div className="action-row">{delivery.status === 'picked_up' ? <button className="btn btn-primary" onClick={onPod} data-testid={`button-pod-${delivery.id}`}><UserRound size={14} /> Capture proof</button> : <button className="btn btn-warn" disabled={busy} onClick={() => onMove(delivery, next)} data-testid={`button-progress-${delivery.id}`}>{delivery.status === 'assigned' ? <><PackageCheck size={14} /> Mark picked up</> : <><Send size={14} /> Mark delivered</>}</button>}</div></article>;
}

function PodDialog({ delivery, onClose, onDone }: { delivery?: any; onClose: () => void; onDone: () => void }) {
  const [name, setName] = useState('');
  const [signature, setSignature] = useState('');
  const [photoUrl, setPhotoUrl] = useState('');
  const pod = useSubmitProofOfDelivery();
  if (!delivery) return null;
  return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><div className="eyebrow">Final handoff · {delivery.reference}</div><div className="modal-title">Proof of delivery</div></div><button className="icon-btn" onClick={onClose} data-testid="button-close-pod"><XIcon /></button></div><form className="modal-body" onSubmit={(e) => { e.preventDefault(); pod.mutate({ id: delivery.id, data: { qrToken: delivery.qrToken, recipientName: name, signatureData: signature || null, photoUrl: photoUrl || null } }, { onSuccess: onDone }); }}><div style={{ background: 'hsl(var(--background))', borderRadius: 8, padding: 15, marginBottom: 16, fontSize: 12 }}><strong>{delivery.customerName}</strong><div className="delivery-sub">{delivery.address}</div></div><div className="form-grid"><div className="form-field"><label htmlFor="recipient-name">Recipient name</label><input id="recipient-name" className="input" required minLength={2} value={name} onChange={(e) => setName(e.target.value)} placeholder="Who received the order?" data-testid="input-recipient-name" /></div><div className="form-field"><label htmlFor="recipient-signature">Signature or initials</label><input id="recipient-signature" className="input" required minLength={1} value={signature} onChange={(e) => setSignature(e.target.value)} placeholder="Type initials to confirm handoff" data-testid="input-recipient-signature" /></div><div className="form-field"><label htmlFor="proof-photo">Photo URL <span style={{ color: 'hsl(var(--muted-foreground))', fontWeight: 500 }}>(optional)</span></label><input id="proof-photo" className="input" value={photoUrl} onChange={(e) => setPhotoUrl(e.target.value)} placeholder="Paste a captured photo link if available" data-testid="input-proof-photo" /></div></div>{pod.isError && <div className="error-state" style={{ marginTop: 13 }}>Proof could not be sent. Keep it open and try again when you have signal.</div>}<div className="form-actions"><button className="btn btn-secondary" type="button" onClick={onClose} data-testid="button-cancel-pod">Not yet</button><button className="btn btn-primary" disabled={pod.isPending} type="submit" data-testid="button-submit-pod"><Check size={14} />{pod.isPending ? 'Sending…' : 'Confirm handoff'}</button></div></form></div></div>;
}
function XIcon() { return <span style={{ fontSize: 18, lineHeight: 1 }}>×</span>; }